plugins {
    id "maven-publish"
    id "base"
    id "java"
}

def getGitCommitCount() {
    def process = "git rev-list --count HEAD".execute()
    process.waitFor()
    return process.text.trim()
}

version = project.mod_version + "+paper" + project.paper_version + "-b" + getGitCommitCount()
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${project.paper_api_version}"
}

sourceSets {
    main {
        java.setSrcDirs(["src/main/java/com/overpoweredmobs/paper"])
    }
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"
    filesMatching("plugin.yml") {
        expand "version": project.version
    }
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}
